name: React CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]

      steps:
        - uses: actions/checkout@v1
        - run: yarn
  

        - name: test build
          run: CI='' yarn build

        - name: Deploy
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: |
            aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            arn:aws:s3:::drawingpr
