name: React CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]

      steps:
        - uses: actions/checkout@v1
        - run: yarn
        - run: yarn build
        - run: yarn test
